# Generated by Django 4.2.7 on 2025-11-28 13:39

import django.core.validators
from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_projectreport_uuid_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreport',
            name='report_file',
            field=models.FileField(help_text='Upload PDF, DOCX, or XLSX files only (Max size: 5MB)', upload_to=reports.models.upload_to_reports, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xlsx']), reports.models.validate_file_size]),
        ),
    ]
